### ISSUE TITLE
Call to undefined function GuzzleHttp\Command\Guzzle\ResponseLocation\simplexml_load_string()

### ISSUE THREAD

**Issue by Georege** [sy-records/wordpress-qcloud-cos#11]
Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\Command\Guzzle\ResponseLocation\simplexml_load_string() in /opt/wordpress/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle-services/src/ResponseLocation/XmlLocation.php:38 Stack trace: #0 /opt/wordpress/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle-services/src/Deserializer.php(156): GuzzleHttp\Command\Guzzle\ResponseLocation\XmlLocation->before(Object(GuzzleHttp\Command\Result), Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Command\Guzzle\Parameter)) #1 /opt/wordpress/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle-services/src/Deserializer.php(199): GuzzleHttp\Command\Guzzle\Deserializer->triggerBeforeVisitor('xml', Object(GuzzleHttp\Command\Guzzle\Parameter), Object(GuzzleHttp\Command\Result), Object(GuzzleHttp\Psr7\Response), Array) #2 /opt/wordpress/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle-services/src/Deserializer.php(116): GuzzleHttp\Command\Guz in /opt/wordpress/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle-services/src/ResponseLocation/XmlLocation.php on line 38

**Comment by Georege** [comment]
the release 1.8.3

**Comment by Georege** [comment]
i found the cause！the new version need php-xml module，long time ago,i used 1.4! it seems not need this!
