### ISSUE TITLE
GuzzleHttp致命错误：Call to undefined method

### ISSUE THREAD

**Issue by AH-dark** [sy-records/wordpress-qcloud-cos#16]
Fatal error: Uncaught Error: Call to undefined method GuzzleHttp\Promise\Coroutine::of() in /data/wwwroot/ahdark.rc0.co/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/functions.php:362 Stack trace: #0 /data/wwwroot/ahdark.rc0.co/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(181): GuzzleHttp\Promise\coroutine() #1 /data/wwwroot/ahdark.rc0.co/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle-services/src/Handler/ValidatedDescriptionHandler.php(79): GuzzleHttp\Command\ServiceClient->GuzzleHttp\Command\{closure}() #2 /data/wwwroot/ahdark.rc0.co/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(85): GuzzleHttp\Command\Guzzle\Handler\ValidatedDescriptionHandler->GuzzleHttp\Command\Guzzle\Handler\{closure}() #3 /data/wwwroot/ahdark.rc0.co/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(77): GuzzleHttp\Command\ServiceClient->executeAsync() #4 / in /data/wwwroot/ahdark.rc0.co/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/functions.php on line 362

**Comment by AH-dark** [comment]
初步判断是与其他插件的GuzzleHttp冲突

以下是我目前的插件列表

![2021/07/26/d01140726122603.png](https://i1.atlascloud.cn/2021/07/26/d01140726122603.png)
